### ISSUE TITLE
Errors in `make` inside `data`

### ISSUE THREAD

**Issue by rtm** [humdrum-tools/humdrum-tools#13]
What is the likely cause of these errors I get when running `make` inside `humdrum-tools/data`? Sorry for the screenshot.

<img width="719" alt="image" src="https://github.com/user-attachments/assets/4ab97fb9-95cc-4f5c-992a-090dd2729b3e">

I am running Ubuntu 22.04 inside WSL.

**Comment by craigsapp** [comment]
Trying to do a new install of humdrum-data, I got the same error as you did in MacOS. 

The main problem seems to be related to renaming `Ano` to `Any` in The 1520s Project repository last month.  This caused a non-existent directory to be processed with the downloading scripts in `humdrum-data`, which what not handled properly (I will have to add checks to avoid problems in such cases). Updating to use `Any` instead of `Ano` seems to fix the problem (the `-v` option error message is probably related to the missing directory, and I will have to check how to refine the script to deal with a missing directory).

I don't know yet where the address "1520s-project.com" is coming from: this is an old address and is now "1520s-project.org" (maybe the `.com` version finally lapsed from DNS).   I found the old address mentioned in the file:
    https://github.com/benory/1520s-project-scores/blob/main/LICENSE.txt
But I don't know if this is related.  The fix from Ano&rarr;Any for anonymous works seems to avoid this problem in any case.

--------------------------

For this error (which did not seem to stop the Makefile):

```
/usr/bin/md5sum: invalid option -- 'q'
```

I was assuming that the `md5sum` in linux had a `-q` option like the `md5` tool in MacOS.   The `-q` option is used to extract only the MD5 checksums without the filenames.   Looking online, I see that the following command can emulate `md5 -q`:

```
md5sum filename | awk '{print $1}'
```

This may still be causing a problem.  I will try downloading in Fedora linux next to see if that is a problem after the download is complete in MacOS that I am currently doing, but I don't have access to Ubuntu in WSL at the moment since I am traveling (I am expecting that Fedora and Ubuntu downloading to be the same).

-----------------

Try downloading humdrum-data like this (there may be some updates to the `humdrum-tools` (related to 1520s-project.com error message) that are needed, which I will also look into, so this will avoid any problems related to that):

```
cd ~/local
git clone https://github.com/humdrum-tools/humdrum-data
cd humdrum-data
make
```

**Comment by craigsapp** [comment]
I will push the Ano&rarr;Any fix soon, so don't try for a few more minutes while I update the README file first.

**Comment by rtm** [comment]
Many thanks for your prompt response. I will try this again this weekend.

**Comment by rtm** [comment]
Linux supports the `--quiet` option to md5sum, but unfortunately macOS doesn't recognize that. Or you could just remove that option and live with "OK" being printed.

**Comment by craigsapp** [comment]
`md5 -q` prevents listing the filename along with the MD5 sum:

```
$ md5 .DS_Store 
MD5 (.DS_Store) = 520b42063d0a1005c454e0b98cb1cfba

$ md5 -q .DS_Store
520b42063d0a1005c454e0b98cb1cfba
```

Who knows why `-q` was chosen for that, as it does not match `md5sum --quiet` which suppresses text when running verification:

```
$ md5sum .bashrc 
4f4cf32553d16d9cc29e1f345061bf24  .bashrc

$ md5sum --quiet .bashrc 
md5sum: the --quiet option is meaningful only when verifying checksums
Try 'md5sum --help' for more information.
```

So to emulate `md5 -q file`, this works: `md5sum file | awk '{print $1}'`:

```
$ md5sum  .bashrc | awk '{print $1}'
4f4cf32553d16d9cc29e1f345061bf24
```

**Comment by craigsapp** [comment]
I have put the updates for the `humdrum-data` repository online (I will check on Fedora linux now).

**Comment by rtm** [comment]
`make` worked properly for data now, thanks for fixing that!

**Comment by craigsapp** [comment]
That is great!  Tell me if there are any problems in the future since I don't check often with WSL/Ubuntu.  I have been making a few enhancements in download in Fedora linux, suppressing some uninteresting messages related to searching for md5 and md5sum with the which command (which prints a message to stderr when it cannot find a program in Fedora, but is silent for the same situation in MacOS).
